### ISSUE TITLE
"Tracker(s)" status language isn't changing after language change of app

### ISSUE THREAD

**Issue by kyoyacchi** [Jays2Kings/tachiyomiJ2K#1431]
### Steps to reproduce

1. Change app language any other than English(or ur native lang)
2. Open a manga to see trackers.
3. You'll see that statuses aren't English (/)

### Expected behavior

It should show it as what language i use.

### Actual behavior

It shows it as Turkish. I want it to show those as English.
![Screenshot_20220929-175738](https://user-images.githubusercontent.com/63583961/193066575-2eb525a4-6e64-447f-a12c-d574878803ae.jpg)
![Screenshot_20220929-175830](https://user-images.githubusercontent.com/63583961/193066799-a3108308-ec4e-4f81-9d5c-764a3c6ddad8.jpg)

### TachiyomiJ2K version

1.5.9

### Android version

Android 11

### Device

Tecno Spark 7T

### Other details

I know it's a beta feature but isn't there any way to show them as English? Clearing cache didn't work. Removing and adding trackings as well.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.9](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.
